import Providers from "../components/Providers";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* Wrap the children with Providers for Redux and other context management */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
